#
# Plugin created by fergydanny (dnyferguson), if you like this check out my other resources at https://www.spigotmc.org/resources/authors/fergydanny.25236/
#
# Use the /punisher command in-game to get a list of all the commands you have access to
#

# Configure your MySQL settings
mysql:
  ip: '127.0.0.1'
  port: '3306'
  username: 'username'
  password: 'password'
  database: 'thepunisher'

# Configure your litebans MySQL settings if you want to import punishments
litebans-mysql:
  ip: '127.0.0.1'
  port: '3306'
  username: 'username'
  password: 'password'
  database: 'litebans'


# Configure your Redis settings
redis:
  ip: '127.0.0.1'
  port: '6379'
  password: ''

# Configure global system settings here

#
# Warnings
#
warning-triggers:
  - '3:/mute %player% 1h [Auto] %reason%'
  - '4:/mute %player% 12h [Auto] %reason%'
  - '5:/kick %player% [Auto] Final warning: %reason%'
  - '6:/ban %player% 1d [Auto] Excessive Warnings'

#
# Mutes
#
blocked-commands-when-muted:
  - '/msg'
  - '/emsg'
  - '/message'
  - '/emessage'
  - '/r'
  - '/er'
  - '/reply'
  - '/ereply'
  - '/tell'
  - '/etell'
  - '/whisper'
  - '/ewhisper'
  - '/me'
  - '/m'
  - '/pm'
  - '/p'
  - '/party'
  - '/is chat'
  - '/island chat'
  - '/is tc'
  - '/marry chat'

#
# Kicks
#

# If the kick reason contains any of the following reasons, it will not be logged/saved
dont-log-reasons:
  - 'restart'
  - 'shutdown'
  - 'reboot'

# Configure messages here
messages:
  punisher-command-header: '&e&lThe Punisher &7(Available Commands: %amount%)'
  punisher-command-list-format: '&e%command% &7- &6%usage%'
  punisher-command-no-available-commands: '&cYou currently have no permissions. Ask management about it!'
