name: ThePunisher
version: ${project.version}
main: com.dnyferguson.thepunisher.ThePunisher
authors: [fergydanny]
api-version: 1.16
description: A feature rich punishment system.
website: https://dnyferguson.com
commands:
  punisher:
    description: Lists available punishment commands.
  ban:
    description: Ban a player.
    aliases: [banip, ipban]
  unban:
    description: Unban a player.
  checkban:
    description: Check if a player is currently banned.
  mute:
    description: Mute a player.
    aliases: [muteip, ipmute]
  unmute:
    description: Unmute a player.
  checkmute:
    description: Check if a player is currently muted.
  alts:
    description: Check whos sharing an ip with a player.
  kick:
    description: Kick a player.
  bypassban:
    description: Allow a specific player to bypass a ban.
  bypassmute:
    description: Allow a specific player to bypass a ban.
  unbypassban:
    description: Remove a player from the bypass bans list.
  unbypassmute:
    description: Remove a player from the bypass mutes list.
  iphistory:
    description: Check a player's ip history.
  warn:
    description: Issue a warning to a player.
  staffrollback:
    description: Roll back a staff member's actions.
  unwarn:
    description: Removes a players last warn.
  history:
    description: View a players recent punishments.
  litebansimport:
    description: Console only import command to import from litebans.
  punishermerge:
    description: Merge punishments to one table.
  clearchat:
    description: Clear chat.