name: ThePunisher
version: ${project.version}
main: com.dnyferguson.thepunisher.ThePunisher
authors: [fergydanny]
description: A feature rich punishment system.
website: https://dnyferguson.com
commands:
  punisher:
    description: Lists available punishment commands.
  ban:
    description: Ban a player.
  unban:
    description: Unban a player.
  checkban:
    description: Check if a player is currently banned.
  mute:
    description: Mute a player.
  unmute:
    description: Unmute a player.
  checkmute:
    description: Check if a player is currently muted.
  alts:
    description: Check whos sharing an ip with a player.
  kick:
    description: Kick a player.
  bypassban:
    description: Allow a specific player to bypass a ban.
  bypassmute:
    description: Allow a specific player to bypass a ban.
  unbypassban:
    description: Remove a player from the bypass bans list.
  unbypassmute:
    description: Remove a player from the bypass mutes list.