name: ThePunisher
version: ${project.version}
main: com.dnyferguson.thepunisher.ThePunisher
authors: [fergydanny]
description: A feature rich punishment system.
website: https://dnyferguson.com
commands:
  punisher:
    description: Lists available punishment commands.
  ban:
    description: Ban a player.
  unban:
    description: Unban a player.
  checkban:
    description: Check if a player is currently banned.
  mute:
    description: Mute a player.
  unmute:
    description: Unmute a player.
  checkmute:
    description: Check if a player is currently muted.