name: ThePunisher
version: ${project.version}
main: com.dnyferguson.thepunisher.ThePunisher
authors: [fergydanny]
description: A feature rich punishment system.
website: https://dnyferguson.com
commands:
  punisher:
    description: Lists available punishment commands.
  ban:
    description: Ban a player.